version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    command: --serviceExecutor adaptive
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build: ./db